Repository mavidurak/orientation-front-end, pull requests merged in 2021-07, with the labels that each got.

#33 api proxy added
  vue.config.js
  yarn.lock
Labels: enhancement

#30 Login and register wiews needs bootstrap
  src/views/guests/Login.vue
  src/views/guests/Register.vue
Labels: bug, ready for review

#38 Content list connected to api
  package-lock.json
  package.json
  src/components/Content/ContentDetailSmall.vue
  src/components/Content/ContentList.vue
  vue.config.js
  yarn.lock
Labels: ready for review
